[package]
name = "wezel_exec"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/wezel-build/wezel_exec"
publish = false
license = "Apache-2.0"

[[bin]]
name = "wezel_exec"
path = "src/main.rs"

[package.metadata.dist]
dist = true

[dependencies]
anyhow = "1"
forager_sdk = { git = "https://github.com/wezel-build/wezel", rev = "1fd8da78b28c0cb250cbf99e59b96c18dae9abcc" }
libc = "0.2"
schemars = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"

[profile.dist]
inherits = "release"
lto = "thin"
